db.codigosEstablecimientos.insertMany([
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.01,
    tipo: "DISPENSARIO DE MEDICAMENTOS - FARMACIAS - DROGUERIAS",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.02,
    tipo: "TIENDAS NATURISTAS",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.03,
    tipo: "DROGUERIAS VETERINARIAS",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.04,
    tipo: "DEPÓSITOS DE MEDICAMENTOS",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.05,
    tipo: "DROGUERIAS ( COMERCIO AL POR MAYOR DE PRODUCTOS FARMACÉUTICOS Y MEDICINALES, COSMÉTICOS Y ARTÍCULOS DE TOCADOR)",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.06,
    tipo: "COMERCIO DE PRODUCTOS TALES COMO: COMERCIO AL POR MENOR DE EQUIPO FOTOGRÁFICO, ÓPTICO Y DE PRECISIÓN. COMERCIO AL POR MENOR DE TODA CLASE DE RELOJES, JOYAS Y ARTÍCULOS DE PLATA EN GENERAL,ARTÍCULOS DE ESOTÉRICOS,TIENDAS DE ARTÍCULOS SEXUALES (SEX-SHOP), FLORISTERIAS,OPTICAS Y GALERIAS",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.07,
    tipo: "CENTROS COMERCIALES",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.08,
    tipo: "ACTIVIDADES DE ENVASE Y EMPAQUE",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.09,
    tipo: "ESTABLECIMIENTOS VETERINARIOS (Criadero Mascotas, Venta de Biológicos, Medicamentos e insumos Veterinarios,  Centros de Atención de Vida Silvestre, Zoocriaderos (destinados a la cria de animales silvestres con fines comerciales, Coso y/o Centro de bienestar animal,  Centro de zoonosis, Guardería y Escuelas de adiestramiento de Mascotas)",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.1,
    tipo: "DEPOSITOS, DEPOSITOS  DE MATERIALES DE CONSTRUCCION, FERRETERIAS, CHATARRERIA (COMERCIO AL POR MAYOR DE MATERIALES DE CONSTRUCCIÓN, ARTÍCULOS DE FERRETERÍA, PINTURAS, PRODUCTOS DE VIDRIO, EQUIPO Y MATERIALES DE FONTANERÍA Y CALEFACCIÓN)",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.11,
    tipo: "BODEGAS DE RECICLAJE",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.12,
    tipo: "CEMENTERIOS (CON O SIN MORGUE)",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.13,
    tipo: "FUNERARIAS (CON O SIN LABORATORIO DE TANATOPRAXIA)",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.14,
    tipo: "MORGUES",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.15,
    tipo: "OSARIOS  - CENIZARIOS - COLOMBIARIOS",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.16,
    tipo: "ESTABLECIMIENTOS DE ENTRETENCION PARA ADULTOS Y SITIOS DE ENCUETNTRO SEXUAL: CASAS DE LENOCINIO,BARES SWINGER,SALAS DE MASAJE ERÓTICO - SAUNAS Y TURCOS PARA POBLACION LGBTI ESTABLECIMIENTOS AFINES",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.17,
    tipo: "SAUNAS, TURCOS, JACUZZI, SPA ",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.18,
    tipo: "GIMNASIO",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.19,
    tipo: "",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.2,
    tipo: "",
    nivelRiesgo: "",
  },
  {
    grupo: "ESTABLECIMIENTOS COMERCIALES",
    codigo: 16.21,
    tipo: "",
    nivelRiesgo: "",
  },
]);
